version: "3.8"

services:
  spring-api:
    container_name: spring-api
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - redis-cluster-net
      - kafka-net
      - elk-net
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ../../.env


  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skytracker
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - redis-cluster-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s


networks:
  redis-cluster-net:
    external: true
  kafka-net:
    external: true
  elk-net:
    external: true


volumes:
  mysql-data: