apiVersion: v1
kind: Namespace
metadata: { name: data }
---
apiVersion: v1
kind: Namespace
metadata: {name: apps}
---
apiVersion: v1
kind: Namespace
metadata: {name: jenkins}
---
apiVersion: v1
kind: Namespace
metadata: {name: kafka}