logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka.clients.consumer: DEBUG

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    client-id: price-collector

    consumer:
      group-id: price-collector-group
      enable-auto-commit: false
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.skytracker.common.dto.alerts.FlightAlertEventMessageDto

        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
        heartbeat.interval.ms: 3000
        session.timeout.ms: 10000

        isolation.level: read_committed

      max-poll-records: 50

    listener:
      type: batch
      ack-mode: manual_immediate
      concurrency: 3
      poll-timeout: 3s
      missing-topics-fatal: false

  data:
    redis:
      password: ${SPRING_DATA_REDIS_PASSWORD}
      sentinel:
        master: ${SPRING_DATA_REDIS_SENTINEL_MASTER}
        nodes: ${SPRING_DATA_REDIS_SENTINEL_NODES}
        password: ${SPRING_DATA_REDIS_PASSWORD}