apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: yeonwu/skytracker-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          envFrom:
            - secretRef:
                name: app-secret

          env:
            # ==== Redis Sentinel 환경 변수 ====
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-redis
                  key: redis-password
            - name: SPRING_DATA_REDIS_SENTINEL_MASTER
              value: "mymaster"
            - name: SPRING_DATA_REDIS_SENTINEL_NODES
              value: "redis-node-0.redis-headless.data.svc.cluster.local:26379,redis-node-1.redis-headless.data.svc.cluster.local:26379,redis-node-2.redis-headless.data.svc.cluster.local:26379"
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-redis
                  key: redis-password
            - name: SPRING_DATA_REDIS_SENTINEL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-redis
                  key: redis-password

            # ==== Elasticsearch 연결 정보 (HTTP, 인증서 X) ====
            - name: ES_URI
              value: http://elastic-es-http.data.svc:9200
            - name: ES_USERNAME
              value: elastic
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-es-elastic-user
                  key: elastic

          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              memory: 1Gi