apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-collector
  namespace: apps
spec:
  replicas: 1
  selector: { matchLabels: { app: price-collector } }
  template:
    metadata: { labels: { app: price-collector } }
    spec:
      containers:
        - name: price-collector
          image: yeonwu/price-collector:latest
          env:
            - { name: SPRING_PROFILES_ACTIVE, value: collector }
            - { name: KAFKA_BOOTSTRAP_SERVERS, value: my-cluster-kafka-bootstrap.kafka.svc:9092 }
          readinessProbe: { httpGet: { path: /actuator/health/readiness, port: 8080 }, initialDelaySeconds: 5 }
          livenessProbe:  { httpGet: { path: /actuator/health/liveness,  port: 8080 }, initialDelaySeconds: 10 }